// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: interaction/v1/interaction_cleanup.proto

// Recorte del contrato de interaction-service con lo unico que este servicio le
// llama: la limpieza de lo que deja atras algo que se borra aqui.
//
// El paquete, el nombre del servicio, el de los metodos y los numeros de campo
// son los mismos que alla, que es lo que define la compatibilidad en el cable;
// el nombre de archivo es distinto para que ambos descriptores puedan convivir.
//
// Mismo criterio que el resto de los stubs de cliente del monorepo: cada
// servicio es dueno de los que usa. Si interaction.proto cambia estos metodos,
// hay que reflejarlo aqui.

package interactionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InteractionService_DeleteUserInteractions_FullMethodName = "/interaction.v1.InteractionService/DeleteUserInteractions"
	InteractionService_DeleteBookInteractions_FullMethodName = "/interaction.v1.InteractionService/DeleteBookInteractions"
)

// InteractionServiceClient is the client API for InteractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InteractionServiceClient interface {
	// Ninguno lleva anotacion HTTP: se llaman directo a interaction-service:50053,
	// sin pasar por el gateway, que ademas corta estas rutas.
	DeleteUserInteractions(ctx context.Context, in *DeleteUserInteractionsRequest, opts ...grpc.CallOption) (*DeleteInteractionsResponse, error)
	DeleteBookInteractions(ctx context.Context, in *DeleteBookInteractionsRequest, opts ...grpc.CallOption) (*DeleteInteractionsResponse, error)
}

type interactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionServiceClient(cc grpc.ClientConnInterface) InteractionServiceClient {
	return &interactionServiceClient{cc}
}

func (c *interactionServiceClient) DeleteUserInteractions(ctx context.Context, in *DeleteUserInteractionsRequest, opts ...grpc.CallOption) (*DeleteInteractionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInteractionsResponse)
	err := c.cc.Invoke(ctx, InteractionService_DeleteUserInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) DeleteBookInteractions(ctx context.Context, in *DeleteBookInteractionsRequest, opts ...grpc.CallOption) (*DeleteInteractionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInteractionsResponse)
	err := c.cc.Invoke(ctx, InteractionService_DeleteBookInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionServiceServer is the server API for InteractionService service.
// All implementations must embed UnimplementedInteractionServiceServer
// for forward compatibility.
type InteractionServiceServer interface {
	// Ninguno lleva anotacion HTTP: se llaman directo a interaction-service:50053,
	// sin pasar por el gateway, que ademas corta estas rutas.
	DeleteUserInteractions(context.Context, *DeleteUserInteractionsRequest) (*DeleteInteractionsResponse, error)
	DeleteBookInteractions(context.Context, *DeleteBookInteractionsRequest) (*DeleteInteractionsResponse, error)
	mustEmbedUnimplementedInteractionServiceServer()
}

// UnimplementedInteractionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractionServiceServer struct{}

func (UnimplementedInteractionServiceServer) DeleteUserInteractions(context.Context, *DeleteUserInteractionsRequest) (*DeleteInteractionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserInteractions not implemented")
}
func (UnimplementedInteractionServiceServer) DeleteBookInteractions(context.Context, *DeleteBookInteractionsRequest) (*DeleteInteractionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBookInteractions not implemented")
}
func (UnimplementedInteractionServiceServer) mustEmbedUnimplementedInteractionServiceServer() {}
func (UnimplementedInteractionServiceServer) testEmbeddedByValue()                            {}

// UnsafeInteractionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionServiceServer will
// result in compilation errors.
type UnsafeInteractionServiceServer interface {
	mustEmbedUnimplementedInteractionServiceServer()
}

func RegisterInteractionServiceServer(s grpc.ServiceRegistrar, srv InteractionServiceServer) {
	// If the following call panics, it indicates UnimplementedInteractionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InteractionService_ServiceDesc, srv)
}

func _InteractionService_DeleteUserInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserInteractionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).DeleteUserInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_DeleteUserInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).DeleteUserInteractions(ctx, req.(*DeleteUserInteractionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_DeleteBookInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookInteractionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).DeleteBookInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_DeleteBookInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).DeleteBookInteractions(ctx, req.(*DeleteBookInteractionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InteractionService_ServiceDesc is the grpc.ServiceDesc for InteractionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InteractionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.v1.InteractionService",
	HandlerType: (*InteractionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteUserInteractions",
			Handler:    _InteractionService_DeleteUserInteractions_Handler,
		},
		{
			MethodName: "DeleteBookInteractions",
			Handler:    _InteractionService_DeleteBookInteractions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interaction/v1/interaction_cleanup.proto",
}
