// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: interaction/v1/interaction_cleanup.proto

// Recorte del contrato de interaction-service con lo unico que este servicio le
// llama: la limpieza de lo que deja atras algo que se borra aqui.
//
// El paquete, el nombre del servicio, el de los metodos y los numeros de campo
// son los mismos que alla, que es lo que define la compatibilidad en el cable;
// el nombre de archivo es distinto para que ambos descriptores puedan convivir.
//
// Mismo criterio que el resto de los stubs de cliente del monorepo: cada
// servicio es dueno de los que usa. Si interaction.proto cambia estos metodos,
// hay que reflejarlo aqui.

package interactionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteUserInteractionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserInteractionsRequest) Reset() {
	*x = DeleteUserInteractionsRequest{}
	mi := &file_interaction_v1_interaction_cleanup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserInteractionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserInteractionsRequest) ProtoMessage() {}

func (x *DeleteUserInteractionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_cleanup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserInteractionsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserInteractionsRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_cleanup_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteUserInteractionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteBookInteractionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookInteractionsRequest) Reset() {
	*x = DeleteBookInteractionsRequest{}
	mi := &file_interaction_v1_interaction_cleanup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookInteractionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookInteractionsRequest) ProtoMessage() {}

func (x *DeleteBookInteractionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_cleanup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookInteractionsRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookInteractionsRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_cleanup_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteBookInteractionsRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type DeleteInteractionsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LikesDeleted    int32                  `protobuf:"varint,1,opt,name=likes_deleted,json=likesDeleted,proto3" json:"likes_deleted,omitempty"`
	CommentsDeleted int32                  `protobuf:"varint,2,opt,name=comments_deleted,json=commentsDeleted,proto3" json:"comments_deleted,omitempty"`
	RatingsDeleted  int32                  `protobuf:"varint,3,opt,name=ratings_deleted,json=ratingsDeleted,proto3" json:"ratings_deleted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteInteractionsResponse) Reset() {
	*x = DeleteInteractionsResponse{}
	mi := &file_interaction_v1_interaction_cleanup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInteractionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInteractionsResponse) ProtoMessage() {}

func (x *DeleteInteractionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_cleanup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInteractionsResponse.ProtoReflect.Descriptor instead.
func (*DeleteInteractionsResponse) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_cleanup_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteInteractionsResponse) GetLikesDeleted() int32 {
	if x != nil {
		return x.LikesDeleted
	}
	return 0
}

func (x *DeleteInteractionsResponse) GetCommentsDeleted() int32 {
	if x != nil {
		return x.CommentsDeleted
	}
	return 0
}

func (x *DeleteInteractionsResponse) GetRatingsDeleted() int32 {
	if x != nil {
		return x.RatingsDeleted
	}
	return 0
}

var File_interaction_v1_interaction_cleanup_proto protoreflect.FileDescriptor

const file_interaction_v1_interaction_cleanup_proto_rawDesc = "" +
	"\n" +
	"(interaction/v1/interaction_cleanup.proto\x12\x0einteraction.v1\"8\n" +
	"\x1dDeleteUserInteractionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x1dDeleteBookInteractionsRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"\x95\x01\n" +
	"\x1aDeleteInteractionsResponse\x12#\n" +
	"\rlikes_deleted\x18\x01 \x01(\x05R\flikesDeleted\x12)\n" +
	"\x10comments_deleted\x18\x02 \x01(\x05R\x0fcommentsDeleted\x12'\n" +
	"\x0fratings_deleted\x18\x03 \x01(\x05R\x0eratingsDeleted2\xfe\x01\n" +
	"\x12InteractionService\x12s\n" +
	"\x16DeleteUserInteractions\x12-.interaction.v1.DeleteUserInteractionsRequest\x1a*.interaction.v1.DeleteInteractionsResponse\x12s\n" +
	"\x16DeleteBookInteractions\x12-.interaction.v1.DeleteBookInteractionsRequest\x1a*.interaction.v1.DeleteInteractionsResponseBmZkgithub.com/EstebanTech/lectonautas/backend/microservices/library-service/proto/interaction/v1;interactionv1b\x06proto3"

var (
	file_interaction_v1_interaction_cleanup_proto_rawDescOnce sync.Once
	file_interaction_v1_interaction_cleanup_proto_rawDescData []byte
)

func file_interaction_v1_interaction_cleanup_proto_rawDescGZIP() []byte {
	file_interaction_v1_interaction_cleanup_proto_rawDescOnce.Do(func() {
		file_interaction_v1_interaction_cleanup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interaction_v1_interaction_cleanup_proto_rawDesc), len(file_interaction_v1_interaction_cleanup_proto_rawDesc)))
	})
	return file_interaction_v1_interaction_cleanup_proto_rawDescData
}

var file_interaction_v1_interaction_cleanup_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_interaction_v1_interaction_cleanup_proto_goTypes = []any{
	(*DeleteUserInteractionsRequest)(nil), // 0: interaction.v1.DeleteUserInteractionsRequest
	(*DeleteBookInteractionsRequest)(nil), // 1: interaction.v1.DeleteBookInteractionsRequest
	(*DeleteInteractionsResponse)(nil),    // 2: interaction.v1.DeleteInteractionsResponse
}
var file_interaction_v1_interaction_cleanup_proto_depIdxs = []int32{
	0, // 0: interaction.v1.InteractionService.DeleteUserInteractions:input_type -> interaction.v1.DeleteUserInteractionsRequest
	1, // 1: interaction.v1.InteractionService.DeleteBookInteractions:input_type -> interaction.v1.DeleteBookInteractionsRequest
	2, // 2: interaction.v1.InteractionService.DeleteUserInteractions:output_type -> interaction.v1.DeleteInteractionsResponse
	2, // 3: interaction.v1.InteractionService.DeleteBookInteractions:output_type -> interaction.v1.DeleteInteractionsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interaction_v1_interaction_cleanup_proto_init() }
func file_interaction_v1_interaction_cleanup_proto_init() {
	if File_interaction_v1_interaction_cleanup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interaction_v1_interaction_cleanup_proto_rawDesc), len(file_interaction_v1_interaction_cleanup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interaction_v1_interaction_cleanup_proto_goTypes,
		DependencyIndexes: file_interaction_v1_interaction_cleanup_proto_depIdxs,
		MessageInfos:      file_interaction_v1_interaction_cleanup_proto_msgTypes,
	}.Build()
	File_interaction_v1_interaction_cleanup_proto = out.File
	file_interaction_v1_interaction_cleanup_proto_goTypes = nil
	file_interaction_v1_interaction_cleanup_proto_depIdxs = nil
}
