// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: user/v1/user_auth.proto

// Recorte del contrato de user-service con lo unico que este servicio le
// llama: ValidateSession. El paquete y los numeros de campo son los mismos que
// alla, que es lo que define la compatibilidad en el cable; el nombre de
// archivo es distinto para que ambos descriptores puedan convivir.
//
// Se mantiene aqui, y no como import del otro modulo, porque cada servicio es
// dueno de los stubs de cliente que usa. Si user.proto cambia ValidateSession,
// hay que reflejarlo en este archivo.

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionRequest) Reset() {
	*x = ValidateSessionRequest{}
	mi := &file_user_v1_user_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionRequest) ProtoMessage() {}

func (x *ValidateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionRequest.ProtoReflect.Descriptor instead.
func (*ValidateSessionRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionResponse) Reset() {
	*x = ValidateSessionResponse{}
	mi := &file_user_v1_user_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionResponse) ProtoMessage() {}

func (x *ValidateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionResponse.ProtoReflect.Descriptor instead.
func (*ValidateSessionResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_user_v1_user_auth_proto protoreflect.FileDescriptor

const file_user_v1_user_auth_proto_rawDesc = "" +
	"\n" +
	"\x17user/v1/user_auth.proto\x12\auser.v1\".\n" +
	"\x16ValidateSessionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"2\n" +
	"\x17ValidateSessionResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2c\n" +
	"\vUserService\x12T\n" +
	"\x0fValidateSession\x12\x1f.user.v1.ValidateSessionRequest\x1a .user.v1.ValidateSessionResponseBcZagithub.com/EstebanTech/lectonautas/backend/microservices/interaction-service/proto/user/v1;userv1b\x06proto3"

var (
	file_user_v1_user_auth_proto_rawDescOnce sync.Once
	file_user_v1_user_auth_proto_rawDescData []byte
)

func file_user_v1_user_auth_proto_rawDescGZIP() []byte {
	file_user_v1_user_auth_proto_rawDescOnce.Do(func() {
		file_user_v1_user_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_auth_proto_rawDesc), len(file_user_v1_user_auth_proto_rawDesc)))
	})
	return file_user_v1_user_auth_proto_rawDescData
}

var file_user_v1_user_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_v1_user_auth_proto_goTypes = []any{
	(*ValidateSessionRequest)(nil),  // 0: user.v1.ValidateSessionRequest
	(*ValidateSessionResponse)(nil), // 1: user.v1.ValidateSessionResponse
}
var file_user_v1_user_auth_proto_depIdxs = []int32{
	0, // 0: user.v1.UserService.ValidateSession:input_type -> user.v1.ValidateSessionRequest
	1, // 1: user.v1.UserService.ValidateSession:output_type -> user.v1.ValidateSessionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_user_auth_proto_init() }
func file_user_v1_user_auth_proto_init() {
	if File_user_v1_user_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_auth_proto_rawDesc), len(file_user_v1_user_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_auth_proto_goTypes,
		DependencyIndexes: file_user_v1_user_auth_proto_depIdxs,
		MessageInfos:      file_user_v1_user_auth_proto_msgTypes,
	}.Build()
	File_user_v1_user_auth_proto = out.File
	file_user_v1_user_auth_proto_goTypes = nil
	file_user_v1_user_auth_proto_depIdxs = nil
}
