// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: interaction/v1/interaction.proto

package interactionv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comment struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	// Quien comento. Va el id y no el nombre: este servicio no es dueno de los
	// perfiles. El cliente los resuelve contra user-service, igual que hace con
	// el author_id de un libro.
	UserId    string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Body      string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Editado alguna vez. Se manda calculado para que el cliente no tenga que
	// comparar las dos fechas.
	Edited        bool `protobuf:"varint,7,opt,name=edited,proto3" json:"edited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Comment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Comment) GetEdited() bool {
	if x != nil {
		return x.Edited
	}
	return false
}

// count es el total de me gusta del libro. liked_by_me solo tiene sentido con
// token: sin el es siempre false.
type LikeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	LikedByMe     bool                   `protobuf:"varint,3,opt,name=liked_by_me,json=likedByMe,proto3" json:"liked_by_me,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeSummary) Reset() {
	*x = LikeSummary{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeSummary) ProtoMessage() {}

func (x *LikeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeSummary.ProtoReflect.Descriptor instead.
func (*LikeSummary) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *LikeSummary) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *LikeSummary) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LikeSummary) GetLikedByMe() bool {
	if x != nil {
		return x.LikedByMe
	}
	return false
}

// average es 0 cuando todavia no hay votos, no null: en proto3 el 0 y el vacio
// son lo mismo, y count = 0 es lo que distingue "sin votos" de "promedio bajo".
type RatingSummary struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BookId  string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Average float64                `protobuf:"fixed64,2,opt,name=average,proto3" json:"average,omitempty"`
	Count   int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// El voto del que pregunta, 0 si no voto o si no vino token.
	MyScore       int32 `protobuf:"varint,4,opt,name=my_score,json=myScore,proto3" json:"my_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingSummary) Reset() {
	*x = RatingSummary{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingSummary) ProtoMessage() {}

func (x *RatingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingSummary.ProtoReflect.Descriptor instead.
func (*RatingSummary) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *RatingSummary) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *RatingSummary) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *RatingSummary) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RatingSummary) GetMyScore() int32 {
	if x != nil {
		return x.MyScore
	}
	return 0
}

type LikeBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeBookRequest) Reset() {
	*x = LikeBookRequest{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeBookRequest) ProtoMessage() {}

func (x *LikeBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeBookRequest.ProtoReflect.Descriptor instead.
func (*LikeBookRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *LikeBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type UnlikeBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeBookRequest) Reset() {
	*x = UnlikeBookRequest{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeBookRequest) ProtoMessage() {}

func (x *UnlikeBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeBookRequest.ProtoReflect.Descriptor instead.
func (*UnlikeBookRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *UnlikeBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type GetBookLikesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookLikesRequest) Reset() {
	*x = GetBookLikesRequest{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookLikesRequest) ProtoMessage() {}

func (x *GetBookLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookLikesRequest.ProtoReflect.Descriptor instead.
func (*GetBookLikesRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{5}
}

func (x *GetBookLikesRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type LikeSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Likes         *LikeSummary           `protobuf:"bytes,1,opt,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeSummaryResponse) Reset() {
	*x = LikeSummaryResponse{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeSummaryResponse) ProtoMessage() {}

func (x *LikeSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeSummaryResponse.ProtoReflect.Descriptor instead.
func (*LikeSummaryResponse) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *LikeSummaryResponse) GetLikes() *LikeSummary {
	if x != nil {
		return x.Likes
	}
	return nil
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCommentRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *CreateCommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ListCommentsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	BookId string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	// Paginacion 1-based. page_size por defecto 20, maximo 100. Los comentarios
	// si se paginan: crecen con los lectores y no tienen techo.
	Page          int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *ListCommentsRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *ListCommentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCommentsResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Comments []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	// Total de comentarios del libro, no cuantos trae esta pagina.
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{9}
}

func (x *ListCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListCommentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommentsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCommentRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *UpdateCommentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCommentRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *DeleteCommentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{12}
}

func (x *CommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type RateBookRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	BookId string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	// De 1 a 5. Fuera de ese rango es InvalidArgument.
	Score         int32 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateBookRequest) Reset() {
	*x = RateBookRequest{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateBookRequest) ProtoMessage() {}

func (x *RateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateBookRequest.ProtoReflect.Descriptor instead.
func (*RateBookRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{13}
}

func (x *RateBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *RateBookRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetBookRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRatingRequest) Reset() {
	*x = GetBookRatingRequest{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRatingRequest) ProtoMessage() {}

func (x *GetBookRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRatingRequest.ProtoReflect.Descriptor instead.
func (*GetBookRatingRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{14}
}

func (x *GetBookRatingRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type DeleteRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRatingRequest) Reset() {
	*x = DeleteRatingRequest{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRatingRequest) ProtoMessage() {}

func (x *DeleteRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRatingRequest.ProtoReflect.Descriptor instead.
func (*DeleteRatingRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRatingRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type RatingSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rating        *RatingSummary         `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingSummaryResponse) Reset() {
	*x = RatingSummaryResponse{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingSummaryResponse) ProtoMessage() {}

func (x *RatingSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingSummaryResponse.ProtoReflect.Descriptor instead.
func (*RatingSummaryResponse) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{16}
}

func (x *RatingSummaryResponse) GetRating() *RatingSummary {
	if x != nil {
		return x.Rating
	}
	return nil
}

type GetBookInteractionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookInteractionsRequest) Reset() {
	*x = GetBookInteractionsRequest{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookInteractionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookInteractionsRequest) ProtoMessage() {}

func (x *GetBookInteractionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookInteractionsRequest.ProtoReflect.Descriptor instead.
func (*GetBookInteractionsRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{17}
}

func (x *GetBookInteractionsRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type BookInteractionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Likes         *LikeSummary           `protobuf:"bytes,1,opt,name=likes,proto3" json:"likes,omitempty"`
	Rating        *RatingSummary         `protobuf:"bytes,2,opt,name=rating,proto3" json:"rating,omitempty"`
	CommentCount  int32                  `protobuf:"varint,3,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookInteractionsResponse) Reset() {
	*x = BookInteractionsResponse{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookInteractionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookInteractionsResponse) ProtoMessage() {}

func (x *BookInteractionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookInteractionsResponse.ProtoReflect.Descriptor instead.
func (*BookInteractionsResponse) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{18}
}

func (x *BookInteractionsResponse) GetLikes() *LikeSummary {
	if x != nil {
		return x.Likes
	}
	return nil
}

func (x *BookInteractionsResponse) GetRating() *RatingSummary {
	if x != nil {
		return x.Rating
	}
	return nil
}

func (x *BookInteractionsResponse) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

type DeleteUserInteractionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserInteractionsRequest) Reset() {
	*x = DeleteUserInteractionsRequest{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserInteractionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserInteractionsRequest) ProtoMessage() {}

func (x *DeleteUserInteractionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserInteractionsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserInteractionsRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteUserInteractionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteBookInteractionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookInteractionsRequest) Reset() {
	*x = DeleteBookInteractionsRequest{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookInteractionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookInteractionsRequest) ProtoMessage() {}

func (x *DeleteBookInteractionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookInteractionsRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookInteractionsRequest) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteBookInteractionsRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

// Los conteos son para el log de quien llama: dejan rastro de cuanto se borro
// en una operacion que no tiene vuelta atras.
type DeleteInteractionsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LikesDeleted    int32                  `protobuf:"varint,1,opt,name=likes_deleted,json=likesDeleted,proto3" json:"likes_deleted,omitempty"`
	CommentsDeleted int32                  `protobuf:"varint,2,opt,name=comments_deleted,json=commentsDeleted,proto3" json:"comments_deleted,omitempty"`
	RatingsDeleted  int32                  `protobuf:"varint,3,opt,name=ratings_deleted,json=ratingsDeleted,proto3" json:"ratings_deleted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteInteractionsResponse) Reset() {
	*x = DeleteInteractionsResponse{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInteractionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInteractionsResponse) ProtoMessage() {}

func (x *DeleteInteractionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInteractionsResponse.ProtoReflect.Descriptor instead.
func (*DeleteInteractionsResponse) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteInteractionsResponse) GetLikesDeleted() int32 {
	if x != nil {
		return x.LikesDeleted
	}
	return 0
}

func (x *DeleteInteractionsResponse) GetCommentsDeleted() int32 {
	if x != nil {
		return x.CommentsDeleted
	}
	return 0
}

func (x *DeleteInteractionsResponse) GetRatingsDeleted() int32 {
	if x != nil {
		return x.RatingsDeleted
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_interaction_v1_interaction_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_v1_interaction_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_interaction_v1_interaction_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_interaction_v1_interaction_proto protoreflect.FileDescriptor

const file_interaction_v1_interaction_proto_rawDesc = "" +
	"\n" +
	" interaction/v1/interaction.proto\x12\x0einteraction.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06edited\x18\a \x01(\bR\x06edited\"\\\n" +
	"\vLikeSummary\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1e\n" +
	"\vliked_by_me\x18\x03 \x01(\bR\tlikedByMe\"s\n" +
	"\rRatingSummary\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x18\n" +
	"\aaverage\x18\x02 \x01(\x01R\aaverage\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x19\n" +
	"\bmy_score\x18\x04 \x01(\x05R\amyScore\"*\n" +
	"\x0fLikeBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\",\n" +
	"\x11UnlikeBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\".\n" +
	"\x13GetBookLikesRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"H\n" +
	"\x13LikeSummaryResponse\x121\n" +
	"\x05likes\x18\x01 \x01(\v2\x1b.interaction.v1.LikeSummaryR\x05likes\"C\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"_\n" +
	"\x13ListCommentsRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x92\x01\n" +
	"\x14ListCommentsResponse\x123\n" +
	"\bcomments\x18\x01 \x03(\v2\x17.interaction.v1.CommentR\bcomments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"S\n" +
	"\x14UpdateCommentRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"?\n" +
	"\x14DeleteCommentRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"D\n" +
	"\x0fCommentResponse\x121\n" +
	"\acomment\x18\x01 \x01(\v2\x17.interaction.v1.CommentR\acomment\"@\n" +
	"\x0fRateBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"/\n" +
	"\x14GetBookRatingRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\".\n" +
	"\x13DeleteRatingRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"N\n" +
	"\x15RatingSummaryResponse\x125\n" +
	"\x06rating\x18\x01 \x01(\v2\x1d.interaction.v1.RatingSummaryR\x06rating\"5\n" +
	"\x1aGetBookInteractionsRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"\xa9\x01\n" +
	"\x18BookInteractionsResponse\x121\n" +
	"\x05likes\x18\x01 \x01(\v2\x1b.interaction.v1.LikeSummaryR\x05likes\x125\n" +
	"\x06rating\x18\x02 \x01(\v2\x1d.interaction.v1.RatingSummaryR\x06rating\x12#\n" +
	"\rcomment_count\x18\x03 \x01(\x05R\fcommentCount\"8\n" +
	"\x1dDeleteUserInteractionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x1dDeleteBookInteractionsRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"\x95\x01\n" +
	"\x1aDeleteInteractionsResponse\x12#\n" +
	"\rlikes_deleted\x18\x01 \x01(\x05R\flikesDeleted\x12)\n" +
	"\x10comments_deleted\x18\x02 \x01(\x05R\x0fcommentsDeleted\x12'\n" +
	"\x0fratings_deleted\x18\x03 \x01(\x05R\x0eratingsDeleted\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8e\r\n" +
	"\x12InteractionService\x12v\n" +
	"\bLikeBook\x12\x1f.interaction.v1.LikeBookRequest\x1a#.interaction.v1.LikeSummaryResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/books/{book_id}/likes\x12w\n" +
	"\n" +
	"UnlikeBook\x12!.interaction.v1.UnlikeBookRequest\x1a#.interaction.v1.LikeSummaryResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/books/{book_id}/likes\x12{\n" +
	"\fGetBookLikes\x12#.interaction.v1.GetBookLikesRequest\x1a#.interaction.v1.LikeSummaryResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/books/{book_id}/likes\x12\x7f\n" +
	"\rCreateComment\x12$.interaction.v1.CreateCommentRequest\x1a\x1f.interaction.v1.CommentResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/books/{book_id}/comments\x12\x7f\n" +
	"\fListComments\x12#.interaction.v1.ListCommentsRequest\x1a$.interaction.v1.ListCommentsResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/books/{book_id}/comments\x12\x84\x01\n" +
	"\rUpdateComment\x12$.interaction.v1.UpdateCommentRequest\x1a\x1f.interaction.v1.CommentResponse\",\x82\xd3\xe4\x93\x02&:\x01*2!/v1/books/{book_id}/comments/{id}\x12\x80\x01\n" +
	"\rDeleteComment\x12$.interaction.v1.DeleteCommentRequest\x1a\x1e.interaction.v1.DeleteResponse\")\x82\xd3\xe4\x93\x02#*!/v1/books/{book_id}/comments/{id}\x12y\n" +
	"\bRateBook\x12\x1f.interaction.v1.RateBookRequest\x1a%.interaction.v1.RatingSummaryResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/v1/books/{book_id}/rating\x12\x80\x01\n" +
	"\rGetBookRating\x12$.interaction.v1.GetBookRatingRequest\x1a%.interaction.v1.RatingSummaryResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/books/{book_id}/rating\x12~\n" +
	"\fDeleteRating\x12#.interaction.v1.DeleteRatingRequest\x1a%.interaction.v1.RatingSummaryResponse\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/books/{book_id}/rating\x12\x95\x01\n" +
	"\x13GetBookInteractions\x12*.interaction.v1.GetBookInteractionsRequest\x1a(.interaction.v1.BookInteractionsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/books/{book_id}/interactions\x12s\n" +
	"\x16DeleteUserInteractions\x12-.interaction.v1.DeleteUserInteractionsRequest\x1a*.interaction.v1.DeleteInteractionsResponse\x12s\n" +
	"\x16DeleteBookInteractions\x12-.interaction.v1.DeleteBookInteractionsRequest\x1a*.interaction.v1.DeleteInteractionsResponseBqZogithub.com/EstebanTech/lectonautas/backend/microservices/interaction-service/proto/interaction/v1;interactionv1b\x06proto3"

var (
	file_interaction_v1_interaction_proto_rawDescOnce sync.Once
	file_interaction_v1_interaction_proto_rawDescData []byte
)

func file_interaction_v1_interaction_proto_rawDescGZIP() []byte {
	file_interaction_v1_interaction_proto_rawDescOnce.Do(func() {
		file_interaction_v1_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interaction_v1_interaction_proto_rawDesc), len(file_interaction_v1_interaction_proto_rawDesc)))
	})
	return file_interaction_v1_interaction_proto_rawDescData
}

var file_interaction_v1_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_interaction_v1_interaction_proto_goTypes = []any{
	(*Comment)(nil),                       // 0: interaction.v1.Comment
	(*LikeSummary)(nil),                   // 1: interaction.v1.LikeSummary
	(*RatingSummary)(nil),                 // 2: interaction.v1.RatingSummary
	(*LikeBookRequest)(nil),               // 3: interaction.v1.LikeBookRequest
	(*UnlikeBookRequest)(nil),             // 4: interaction.v1.UnlikeBookRequest
	(*GetBookLikesRequest)(nil),           // 5: interaction.v1.GetBookLikesRequest
	(*LikeSummaryResponse)(nil),           // 6: interaction.v1.LikeSummaryResponse
	(*CreateCommentRequest)(nil),          // 7: interaction.v1.CreateCommentRequest
	(*ListCommentsRequest)(nil),           // 8: interaction.v1.ListCommentsRequest
	(*ListCommentsResponse)(nil),          // 9: interaction.v1.ListCommentsResponse
	(*UpdateCommentRequest)(nil),          // 10: interaction.v1.UpdateCommentRequest
	(*DeleteCommentRequest)(nil),          // 11: interaction.v1.DeleteCommentRequest
	(*CommentResponse)(nil),               // 12: interaction.v1.CommentResponse
	(*RateBookRequest)(nil),               // 13: interaction.v1.RateBookRequest
	(*GetBookRatingRequest)(nil),          // 14: interaction.v1.GetBookRatingRequest
	(*DeleteRatingRequest)(nil),           // 15: interaction.v1.DeleteRatingRequest
	(*RatingSummaryResponse)(nil),         // 16: interaction.v1.RatingSummaryResponse
	(*GetBookInteractionsRequest)(nil),    // 17: interaction.v1.GetBookInteractionsRequest
	(*BookInteractionsResponse)(nil),      // 18: interaction.v1.BookInteractionsResponse
	(*DeleteUserInteractionsRequest)(nil), // 19: interaction.v1.DeleteUserInteractionsRequest
	(*DeleteBookInteractionsRequest)(nil), // 20: interaction.v1.DeleteBookInteractionsRequest
	(*DeleteInteractionsResponse)(nil),    // 21: interaction.v1.DeleteInteractionsResponse
	(*DeleteResponse)(nil),                // 22: interaction.v1.DeleteResponse
	(*timestamppb.Timestamp)(nil),         // 23: google.protobuf.Timestamp
}
var file_interaction_v1_interaction_proto_depIdxs = []int32{
	23, // 0: interaction.v1.Comment.created_at:type_name -> google.protobuf.Timestamp
	23, // 1: interaction.v1.Comment.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: interaction.v1.LikeSummaryResponse.likes:type_name -> interaction.v1.LikeSummary
	0,  // 3: interaction.v1.ListCommentsResponse.comments:type_name -> interaction.v1.Comment
	0,  // 4: interaction.v1.CommentResponse.comment:type_name -> interaction.v1.Comment
	2,  // 5: interaction.v1.RatingSummaryResponse.rating:type_name -> interaction.v1.RatingSummary
	1,  // 6: interaction.v1.BookInteractionsResponse.likes:type_name -> interaction.v1.LikeSummary
	2,  // 7: interaction.v1.BookInteractionsResponse.rating:type_name -> interaction.v1.RatingSummary
	3,  // 8: interaction.v1.InteractionService.LikeBook:input_type -> interaction.v1.LikeBookRequest
	4,  // 9: interaction.v1.InteractionService.UnlikeBook:input_type -> interaction.v1.UnlikeBookRequest
	5,  // 10: interaction.v1.InteractionService.GetBookLikes:input_type -> interaction.v1.GetBookLikesRequest
	7,  // 11: interaction.v1.InteractionService.CreateComment:input_type -> interaction.v1.CreateCommentRequest
	8,  // 12: interaction.v1.InteractionService.ListComments:input_type -> interaction.v1.ListCommentsRequest
	10, // 13: interaction.v1.InteractionService.UpdateComment:input_type -> interaction.v1.UpdateCommentRequest
	11, // 14: interaction.v1.InteractionService.DeleteComment:input_type -> interaction.v1.DeleteCommentRequest
	13, // 15: interaction.v1.InteractionService.RateBook:input_type -> interaction.v1.RateBookRequest
	14, // 16: interaction.v1.InteractionService.GetBookRating:input_type -> interaction.v1.GetBookRatingRequest
	15, // 17: interaction.v1.InteractionService.DeleteRating:input_type -> interaction.v1.DeleteRatingRequest
	17, // 18: interaction.v1.InteractionService.GetBookInteractions:input_type -> interaction.v1.GetBookInteractionsRequest
	19, // 19: interaction.v1.InteractionService.DeleteUserInteractions:input_type -> interaction.v1.DeleteUserInteractionsRequest
	20, // 20: interaction.v1.InteractionService.DeleteBookInteractions:input_type -> interaction.v1.DeleteBookInteractionsRequest
	6,  // 21: interaction.v1.InteractionService.LikeBook:output_type -> interaction.v1.LikeSummaryResponse
	6,  // 22: interaction.v1.InteractionService.UnlikeBook:output_type -> interaction.v1.LikeSummaryResponse
	6,  // 23: interaction.v1.InteractionService.GetBookLikes:output_type -> interaction.v1.LikeSummaryResponse
	12, // 24: interaction.v1.InteractionService.CreateComment:output_type -> interaction.v1.CommentResponse
	9,  // 25: interaction.v1.InteractionService.ListComments:output_type -> interaction.v1.ListCommentsResponse
	12, // 26: interaction.v1.InteractionService.UpdateComment:output_type -> interaction.v1.CommentResponse
	22, // 27: interaction.v1.InteractionService.DeleteComment:output_type -> interaction.v1.DeleteResponse
	16, // 28: interaction.v1.InteractionService.RateBook:output_type -> interaction.v1.RatingSummaryResponse
	16, // 29: interaction.v1.InteractionService.GetBookRating:output_type -> interaction.v1.RatingSummaryResponse
	16, // 30: interaction.v1.InteractionService.DeleteRating:output_type -> interaction.v1.RatingSummaryResponse
	18, // 31: interaction.v1.InteractionService.GetBookInteractions:output_type -> interaction.v1.BookInteractionsResponse
	21, // 32: interaction.v1.InteractionService.DeleteUserInteractions:output_type -> interaction.v1.DeleteInteractionsResponse
	21, // 33: interaction.v1.InteractionService.DeleteBookInteractions:output_type -> interaction.v1.DeleteInteractionsResponse
	21, // [21:34] is the sub-list for method output_type
	8,  // [8:21] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_interaction_v1_interaction_proto_init() }
func file_interaction_v1_interaction_proto_init() {
	if File_interaction_v1_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interaction_v1_interaction_proto_rawDesc), len(file_interaction_v1_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interaction_v1_interaction_proto_goTypes,
		DependencyIndexes: file_interaction_v1_interaction_proto_depIdxs,
		MessageInfos:      file_interaction_v1_interaction_proto_msgTypes,
	}.Build()
	File_interaction_v1_interaction_proto = out.File
	file_interaction_v1_interaction_proto_goTypes = nil
	file_interaction_v1_interaction_proto_depIdxs = nil
}
