// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: interaction/v1/interaction.proto

package interactionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InteractionService_LikeBook_FullMethodName               = "/interaction.v1.InteractionService/LikeBook"
	InteractionService_UnlikeBook_FullMethodName             = "/interaction.v1.InteractionService/UnlikeBook"
	InteractionService_GetBookLikes_FullMethodName           = "/interaction.v1.InteractionService/GetBookLikes"
	InteractionService_CreateComment_FullMethodName          = "/interaction.v1.InteractionService/CreateComment"
	InteractionService_ListComments_FullMethodName           = "/interaction.v1.InteractionService/ListComments"
	InteractionService_UpdateComment_FullMethodName          = "/interaction.v1.InteractionService/UpdateComment"
	InteractionService_DeleteComment_FullMethodName          = "/interaction.v1.InteractionService/DeleteComment"
	InteractionService_RateBook_FullMethodName               = "/interaction.v1.InteractionService/RateBook"
	InteractionService_GetBookRating_FullMethodName          = "/interaction.v1.InteractionService/GetBookRating"
	InteractionService_DeleteRating_FullMethodName           = "/interaction.v1.InteractionService/DeleteRating"
	InteractionService_GetBookInteractions_FullMethodName    = "/interaction.v1.InteractionService/GetBookInteractions"
	InteractionService_DeleteUserInteractions_FullMethodName = "/interaction.v1.InteractionService/DeleteUserInteractions"
	InteractionService_DeleteBookInteractions_FullMethodName = "/interaction.v1.InteractionService/DeleteBookInteractions"
)

// InteractionServiceClient is the client API for InteractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InteractionService es lo que el lector hace con la obra ajena: me gusta,
// comentarios y calificaciones. La obra en si es de library-service, que no
// sabe nada de esto.
//
// Los libros y los usuarios viven en otras bases, asi que aqui sus ids son UUID
// planos y sin foreign key. Que el libro exista y este publicado se comprueba
// contra library-service en cada escritura, no con una FK.
//
// Ademas del API de peticion/respuesta, el servicio publica lo que va pasando
// en un WebSocket que NO se describe aqui: no es gRPC y no pasa por el
// transcoder. Vive en GET /v1/ws/books/{bookId} y esta documentado en el
// README.
type InteractionServiceClient interface {
	// Dar me gusta es idempotente: repetirlo no suma dos veces ni falla, deja el
	// mismo estado y devuelve el conteo. Asi un doble clic o un reintento de red
	// no obligan al cliente a distinguir "ya estaba".
	LikeBook(ctx context.Context, in *LikeBookRequest, opts ...grpc.CallOption) (*LikeSummaryResponse, error)
	// Quitarlo tambien es idempotente, por la misma razon.
	UnlikeBook(ctx context.Context, in *UnlikeBookRequest, opts ...grpc.CallOption) (*LikeSummaryResponse, error)
	// El conteo del libro. El token es opcional: con el, la respuesta ademas dice
	// si el que pregunta ya dio me gusta.
	GetBookLikes(ctx context.Context, in *GetBookLikesRequest, opts ...grpc.CallOption) (*LikeSummaryResponse, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CommentResponse, error)
	// Listado publico y paginado, del mas nuevo al mas viejo.
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	// Solo el autor del comentario puede editarlo.
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*CommentResponse, error)
	// Lo borra su autor. El autor del libro tambien puede, para poder moderar lo
	// que se dice en su obra.
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Un lector tiene una sola calificacion por libro: volver a calificar la
	// reemplaza, no agrega otra. Por eso es PUT y no POST.
	RateBook(ctx context.Context, in *RateBookRequest, opts ...grpc.CallOption) (*RatingSummaryResponse, error)
	// Promedio y cantidad de votos. Con token, ademas el voto propio.
	GetBookRating(ctx context.Context, in *GetBookRatingRequest, opts ...grpc.CallOption) (*RatingSummaryResponse, error)
	DeleteRating(ctx context.Context, in *DeleteRatingRequest, opts ...grpc.CallOption) (*RatingSummaryResponse, error)
	// Todo lo de un libro en una sola llamada, que es lo que necesita su ficha:
	// pedirlo suelto serian tres viajes para pintar la misma pantalla.
	GetBookInteractions(ctx context.Context, in *GetBookInteractionsRequest, opts ...grpc.CallOption) (*BookInteractionsResponse, error)
	// DeleteUserInteractions borra todo lo que dejo un usuario que se da de baja:
	// sus me gusta, sus comentarios y sus calificaciones. Lo llama user-service,
	// porque el CASCADE de Postgres no cruza de una base de datos a otra.
	//
	// DeleteBookInteractions hace lo mismo con un libro borrado, y lo llama
	// library-service. Sin esto quedarian comentarios colgando de un libro que ya
	// no existe.
	//
	// Ninguna de las dos lleva anotacion google.api.http, asi que no existen como
	// endpoint REST, y ademas quedan bloqueadas en envoy.yaml para que no se
	// alcancen por la ruta de passthrough de gRPC.
	DeleteUserInteractions(ctx context.Context, in *DeleteUserInteractionsRequest, opts ...grpc.CallOption) (*DeleteInteractionsResponse, error)
	DeleteBookInteractions(ctx context.Context, in *DeleteBookInteractionsRequest, opts ...grpc.CallOption) (*DeleteInteractionsResponse, error)
}

type interactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionServiceClient(cc grpc.ClientConnInterface) InteractionServiceClient {
	return &interactionServiceClient{cc}
}

func (c *interactionServiceClient) LikeBook(ctx context.Context, in *LikeBookRequest, opts ...grpc.CallOption) (*LikeSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeSummaryResponse)
	err := c.cc.Invoke(ctx, InteractionService_LikeBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) UnlikeBook(ctx context.Context, in *UnlikeBookRequest, opts ...grpc.CallOption) (*LikeSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeSummaryResponse)
	err := c.cc.Invoke(ctx, InteractionService_UnlikeBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) GetBookLikes(ctx context.Context, in *GetBookLikesRequest, opts ...grpc.CallOption) (*LikeSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeSummaryResponse)
	err := c.cc.Invoke(ctx, InteractionService_GetBookLikes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, InteractionService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, InteractionService_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*CommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, InteractionService_UpdateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, InteractionService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) RateBook(ctx context.Context, in *RateBookRequest, opts ...grpc.CallOption) (*RatingSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatingSummaryResponse)
	err := c.cc.Invoke(ctx, InteractionService_RateBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) GetBookRating(ctx context.Context, in *GetBookRatingRequest, opts ...grpc.CallOption) (*RatingSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatingSummaryResponse)
	err := c.cc.Invoke(ctx, InteractionService_GetBookRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) DeleteRating(ctx context.Context, in *DeleteRatingRequest, opts ...grpc.CallOption) (*RatingSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatingSummaryResponse)
	err := c.cc.Invoke(ctx, InteractionService_DeleteRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) GetBookInteractions(ctx context.Context, in *GetBookInteractionsRequest, opts ...grpc.CallOption) (*BookInteractionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookInteractionsResponse)
	err := c.cc.Invoke(ctx, InteractionService_GetBookInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) DeleteUserInteractions(ctx context.Context, in *DeleteUserInteractionsRequest, opts ...grpc.CallOption) (*DeleteInteractionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInteractionsResponse)
	err := c.cc.Invoke(ctx, InteractionService_DeleteUserInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) DeleteBookInteractions(ctx context.Context, in *DeleteBookInteractionsRequest, opts ...grpc.CallOption) (*DeleteInteractionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInteractionsResponse)
	err := c.cc.Invoke(ctx, InteractionService_DeleteBookInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionServiceServer is the server API for InteractionService service.
// All implementations must embed UnimplementedInteractionServiceServer
// for forward compatibility.
//
// InteractionService es lo que el lector hace con la obra ajena: me gusta,
// comentarios y calificaciones. La obra en si es de library-service, que no
// sabe nada de esto.
//
// Los libros y los usuarios viven en otras bases, asi que aqui sus ids son UUID
// planos y sin foreign key. Que el libro exista y este publicado se comprueba
// contra library-service en cada escritura, no con una FK.
//
// Ademas del API de peticion/respuesta, el servicio publica lo que va pasando
// en un WebSocket que NO se describe aqui: no es gRPC y no pasa por el
// transcoder. Vive en GET /v1/ws/books/{bookId} y esta documentado en el
// README.
type InteractionServiceServer interface {
	// Dar me gusta es idempotente: repetirlo no suma dos veces ni falla, deja el
	// mismo estado y devuelve el conteo. Asi un doble clic o un reintento de red
	// no obligan al cliente a distinguir "ya estaba".
	LikeBook(context.Context, *LikeBookRequest) (*LikeSummaryResponse, error)
	// Quitarlo tambien es idempotente, por la misma razon.
	UnlikeBook(context.Context, *UnlikeBookRequest) (*LikeSummaryResponse, error)
	// El conteo del libro. El token es opcional: con el, la respuesta ademas dice
	// si el que pregunta ya dio me gusta.
	GetBookLikes(context.Context, *GetBookLikesRequest) (*LikeSummaryResponse, error)
	CreateComment(context.Context, *CreateCommentRequest) (*CommentResponse, error)
	// Listado publico y paginado, del mas nuevo al mas viejo.
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	// Solo el autor del comentario puede editarlo.
	UpdateComment(context.Context, *UpdateCommentRequest) (*CommentResponse, error)
	// Lo borra su autor. El autor del libro tambien puede, para poder moderar lo
	// que se dice en su obra.
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteResponse, error)
	// Un lector tiene una sola calificacion por libro: volver a calificar la
	// reemplaza, no agrega otra. Por eso es PUT y no POST.
	RateBook(context.Context, *RateBookRequest) (*RatingSummaryResponse, error)
	// Promedio y cantidad de votos. Con token, ademas el voto propio.
	GetBookRating(context.Context, *GetBookRatingRequest) (*RatingSummaryResponse, error)
	DeleteRating(context.Context, *DeleteRatingRequest) (*RatingSummaryResponse, error)
	// Todo lo de un libro en una sola llamada, que es lo que necesita su ficha:
	// pedirlo suelto serian tres viajes para pintar la misma pantalla.
	GetBookInteractions(context.Context, *GetBookInteractionsRequest) (*BookInteractionsResponse, error)
	// DeleteUserInteractions borra todo lo que dejo un usuario que se da de baja:
	// sus me gusta, sus comentarios y sus calificaciones. Lo llama user-service,
	// porque el CASCADE de Postgres no cruza de una base de datos a otra.
	//
	// DeleteBookInteractions hace lo mismo con un libro borrado, y lo llama
	// library-service. Sin esto quedarian comentarios colgando de un libro que ya
	// no existe.
	//
	// Ninguna de las dos lleva anotacion google.api.http, asi que no existen como
	// endpoint REST, y ademas quedan bloqueadas en envoy.yaml para que no se
	// alcancen por la ruta de passthrough de gRPC.
	DeleteUserInteractions(context.Context, *DeleteUserInteractionsRequest) (*DeleteInteractionsResponse, error)
	DeleteBookInteractions(context.Context, *DeleteBookInteractionsRequest) (*DeleteInteractionsResponse, error)
	mustEmbedUnimplementedInteractionServiceServer()
}

// UnimplementedInteractionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractionServiceServer struct{}

func (UnimplementedInteractionServiceServer) LikeBook(context.Context, *LikeBookRequest) (*LikeSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeBook not implemented")
}
func (UnimplementedInteractionServiceServer) UnlikeBook(context.Context, *UnlikeBookRequest) (*LikeSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlikeBook not implemented")
}
func (UnimplementedInteractionServiceServer) GetBookLikes(context.Context, *GetBookLikesRequest) (*LikeSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookLikes not implemented")
}
func (UnimplementedInteractionServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*CommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedInteractionServiceServer) ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedInteractionServiceServer) UpdateComment(context.Context, *UpdateCommentRequest) (*CommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedInteractionServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedInteractionServiceServer) RateBook(context.Context, *RateBookRequest) (*RatingSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RateBook not implemented")
}
func (UnimplementedInteractionServiceServer) GetBookRating(context.Context, *GetBookRatingRequest) (*RatingSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookRating not implemented")
}
func (UnimplementedInteractionServiceServer) DeleteRating(context.Context, *DeleteRatingRequest) (*RatingSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRating not implemented")
}
func (UnimplementedInteractionServiceServer) GetBookInteractions(context.Context, *GetBookInteractionsRequest) (*BookInteractionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookInteractions not implemented")
}
func (UnimplementedInteractionServiceServer) DeleteUserInteractions(context.Context, *DeleteUserInteractionsRequest) (*DeleteInteractionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserInteractions not implemented")
}
func (UnimplementedInteractionServiceServer) DeleteBookInteractions(context.Context, *DeleteBookInteractionsRequest) (*DeleteInteractionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBookInteractions not implemented")
}
func (UnimplementedInteractionServiceServer) mustEmbedUnimplementedInteractionServiceServer() {}
func (UnimplementedInteractionServiceServer) testEmbeddedByValue()                            {}

// UnsafeInteractionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionServiceServer will
// result in compilation errors.
type UnsafeInteractionServiceServer interface {
	mustEmbedUnimplementedInteractionServiceServer()
}

func RegisterInteractionServiceServer(s grpc.ServiceRegistrar, srv InteractionServiceServer) {
	// If the following call panics, it indicates UnimplementedInteractionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InteractionService_ServiceDesc, srv)
}

func _InteractionService_LikeBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).LikeBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_LikeBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).LikeBook(ctx, req.(*LikeBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_UnlikeBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).UnlikeBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_UnlikeBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).UnlikeBook(ctx, req.(*UnlikeBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_GetBookLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).GetBookLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_GetBookLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).GetBookLikes(ctx, req.(*GetBookLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_RateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).RateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_RateBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).RateBook(ctx, req.(*RateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_GetBookRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).GetBookRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_GetBookRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).GetBookRating(ctx, req.(*GetBookRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_DeleteRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).DeleteRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_DeleteRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).DeleteRating(ctx, req.(*DeleteRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_GetBookInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookInteractionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).GetBookInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_GetBookInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).GetBookInteractions(ctx, req.(*GetBookInteractionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_DeleteUserInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserInteractionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).DeleteUserInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_DeleteUserInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).DeleteUserInteractions(ctx, req.(*DeleteUserInteractionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_DeleteBookInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookInteractionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).DeleteBookInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_DeleteBookInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).DeleteBookInteractions(ctx, req.(*DeleteBookInteractionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InteractionService_ServiceDesc is the grpc.ServiceDesc for InteractionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InteractionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.v1.InteractionService",
	HandlerType: (*InteractionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LikeBook",
			Handler:    _InteractionService_LikeBook_Handler,
		},
		{
			MethodName: "UnlikeBook",
			Handler:    _InteractionService_UnlikeBook_Handler,
		},
		{
			MethodName: "GetBookLikes",
			Handler:    _InteractionService_GetBookLikes_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _InteractionService_CreateComment_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _InteractionService_ListComments_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _InteractionService_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _InteractionService_DeleteComment_Handler,
		},
		{
			MethodName: "RateBook",
			Handler:    _InteractionService_RateBook_Handler,
		},
		{
			MethodName: "GetBookRating",
			Handler:    _InteractionService_GetBookRating_Handler,
		},
		{
			MethodName: "DeleteRating",
			Handler:    _InteractionService_DeleteRating_Handler,
		},
		{
			MethodName: "GetBookInteractions",
			Handler:    _InteractionService_GetBookInteractions_Handler,
		},
		{
			MethodName: "DeleteUserInteractions",
			Handler:    _InteractionService_DeleteUserInteractions_Handler,
		},
		{
			MethodName: "DeleteBookInteractions",
			Handler:    _InteractionService_DeleteBookInteractions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interaction/v1/interaction.proto",
}
